name: dolin_demo_flutter
version: 1.0.0+1
publish_to: none
description: Flutter 学习总结

# 写死 SDK 版本号：避免因为跨 SDK 版本出现的 API 差异进而导致工程问题
environment:
  sdk: 2.18.6
  flutter: 3.3.10

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.0
  shared_preferences: ^2.0.18
  get: 4.6.5
  flutter_html: ^2.2.1
  flutter_swiper_view: ^1.1.8

  # 瀑布流
  flutter_staggered_grid_view: ^0.6.2
  # 屏幕适配
  flutter_screenutil: ^5.7.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: iconFonts
      fonts:
        - asset: assets/fonts/iconfont.ttf
