name: dolin_demo_flutter
version: 1.0.0+1
publish_to: none
description: Flutter 学习总结

# 写死 SDK 版本号：避免因为跨 SDK 版本出现的 API 差异进而导致工程问题
environment:
  sdk: 2.19.6
  flutter: 3.7.10

dependencies:
  cupertino_icons: ^1.0.2
  dio: 5.1.0
  shared_preferences: ^2.0.18
  get: 4.6.5
  flutter_html: ^2.2.1
  flutter_swiper_view: ^1.1.8
  fluttertoast: ^8.2.1
  pull_to_refresh: ^2.0.0
  underline_indicator: ^0.0.4

  # 照片选择
  wechat_assets_picker: ^8.4.1
  # 瀑布流
  flutter_staggered_grid_view: ^0.6.2
  # 屏幕适配
  flutter_screenutil: ^5.7.0
  # 监听 widget 展示到屏幕，埋点用
  visibility_detector: ^0.4.0+2
  # 验证码输入
  pin_code_fields: ^7.4.0
  # 省市区选择器
  city_pickers: ^1.2.1
  # 加密
  crypto: ^3.0.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# 依赖覆写，可用于修改库中 bug
dependency_overrides:
  underline_indicator:
    git:
      url: https://github.com/helloDolin/underline_indicator.git
      ref: master

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: iconFonts
      fonts:
        - asset: assets/fonts/iconfont.ttf
